---
Authors: Molly Honecker and Laura Steeves
---

# Library and data loading

```{r libraries, error = F, message = F}

library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggthemes)
library(readxl)
library(dplyr)
library(rstatix)
library(plotrix)
library(foreign)
library(agricolae)
library(wesanderson)
library(ggsci)
library(forcats) 

```

```{r surf_data, error = F, message = F}

## load in dataset

surfclams <- read.csv("C:/Users/molly/Desktop/research/steeves + munroe - surfclam OA (rios 2023)/data + code/SurfclamsOAandTemp_Fall2023/Biodeposition_ForR.csv")

surfclams$TempTreatment <- factor(surfclams$TempTreatment, levels=c("Low", "Medium", "High"))
surfclams$PhTreatment <- factor(surfclams$PhTreatment, levels=c("Low", "Medium", "High"))

```

```{r dataframes, error = F, message = F}

## create separate datasets for each temp. and pH treatment for ANOVA

surfclams_Temp_High <- surfclams[surfclams$TempTreatment == "High",]
surfclams_Temp_Medium <- surfclams[surfclams$TempTreatment == "Medium",]
surfclams_Temp_Low <- surfclams[surfclams$TempTreatment == "Low",]

surfclams_Ph_High <- surfclams[surfclams$PhTreatment == "High",]
surfclams_Ph_Medium <- surfclams[surfclams$PhTreatment == "Medium",]
surfclams_Ph_Low <- surfclams[surfclams$PhTreatment == "Low",]

```

# Template code

## EDA: Means and SE

```{r VARIABLE_means, error = F, message = F}

## Split data into groups of interest for means and SE, then find mean and SE of each group

means_VARIABLE <- 
  surfclams %>%
  group_by(COLUMNS_TO_GROUP_BY) %>%
  summarise_at(vars(VARIABLE), list(name = mean, 
  ##  std.error in package plotrix, probably way to do in base R but I didn't do for now 
                                    std.error))

## Copy output table onto clipboard for transfer to Excel for ease of analysis

write_excel_csv(means_VARIABLE, "clipboard", row.names = F)

```

## Two-way AOV

```{r VARIABLE_twowayaov_FullDescriptionTemplate, message = F, error = F}

surfclams %>% sample_n_by(TempTreatment, PhTreatment, size=1)

model_twowayaov_template <- lm(log(VARIABLE) ~ TempTreatment + PhTreatment, 
                               data = surfclams)

# Create a QQ plot of residuals

ggqqplot(residuals(model_twowayaov_template))

# Compute Shapiro-Wilk test (normality)

shapiro_test(residuals(model_twowayaov_template))

# check for violation of levene test (equal variance)

surfclams %>% levene_test(OIR_Std ~ TempTreatment*PhTreatment)

```

## Plot 1

Plot style used in Honecker RIOS Summer 23 surfclam pH stress over time project.

```{r VARIABLE_twowayaov_boxplot_FullDescriptionTemplate, error=F, message=FALSE}

## Input desired file path for result and desired dimensions 

png("FILEPATH", width = NUMBER, height = NUMBER)

## Create boxplot

BOXPLOT <- ggboxplot(surfclams, x = "Treatment", y = "VAR", 
                     
## Facet by experiment, split within experiment by size class
                     
  color = "SizeClass", facet.by = "Experiment", lwd = 0.8) +
  
## add dots for each individual
  
  geom_point(position = position_jitterdodge(), alpha = 0.5, aes(x = Treatment, color = SizeClass)) +
  
## Formatting
  
  theme(legend.position = "right") +
  theme_classic() +
  labs(y = "LABEL")

CRstd_box + theme(axis.title = element_text(size = 16),
                  axis.text = element_text(size = 14, color = "black"),
                  legend.title = element_text(size = 16),
                  legend.text = element_text(size = 14),
                  strip.text.x = element_text(size = 16)) + scale_color_manual(name = "Temp/pH group",
                               values = c("#44bb99", "#f8a163"))

dev.off()

```

```{r VARIABLE_twowayaov_boxplot_SimpleTemplate, error = FALSE, message = FALSE}

png("FILEPATH", width = 750, height = 350)

BOXPLOT <- ggboxplot(surfclams, x = "Treatment", y = "VAR", 
  color = "SizeClass", facet.by = "Experiment", lwd = 0.8) +
  geom_point(position = position_jitterdodge(), alpha = 0.5, 
             aes(x = Treatment, color = SizeClass)) +
  theme(legend.position = "right") +
  theme_classic() +
  labs(y = "LABEL")

BOXPLOT + theme(axis.title = element_text(size = 16),
                  axis.text = element_text(size = 14, color = "black"),
                  legend.title = element_text(size = 16),
                  legend.text = element_text(size = 14),
                  strip.text.x = element_text(size = 16)) + 
  scale_color_manual(name = "Size group",
                               values = c("#44bb99", "#f8a163"))

BOXPLOT

dev.off()

```

## Plot 2

```{r, VARIABLE_twowayaov_boxplotV2_SimpleTemplate, error = F, message = F}

png("FILEPATH", width = 750, height = 350)

BOXPLOTV2 <- ggplot(surfclams, aes(y = RESPONSE, x=TREATMENT1, fill=TREATMENT2, order=TREATMENT2))+
  geom_boxplot()+
  geom_point(aes(colour = TREATMENT2), position = position_jitterdodge())+
  scale_color_grey()+
  scale_fill_grey()+
  scale_x_discrete(labels = c('Low', 'Medium', 'High'))+ ##check this
  theme(axis.ticks.length=unit(.5, "cm"))+
  xlab("")+
  ylab("RESPONSE\n(UNITS)")+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2), legend.position= "none")+
  theme(text = element_text(size = 30))+
  labs(fill = "TREATMENT2")+
  labs(colour = "TREATMENT2")+
  geom_pwc(
    aes(group = TREATMENT2), CR_Std = 0,
    method = "t_test", label = "p.adj.format",
    bracket.nudge.y = +0.1
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
  #stat_compare_means(label="p.format")
  #stat_compare_means(aes(group = Treatment), label = "p.format")

BOXPLOTV2

dev.off()

```

## CR

```{r CR_twowayaov_boxplot_SimpleTemplate, error = FALSE, message = FALSE}

png("C:/Users/molly/Desktop/research/steeves + munroe - surfclam OA (rios 2023)/data + code/SurfclamsOAandTemp_Fall2023/CR_Std_Box1.png", width = 750, height = 550)

CRstd_box <- ggboxplot(surfclams, x = "PhTreatment", y = "CR_Std_Weight", 
  color = "TempTreatment", lwd = 0.8) +
  geom_point(position = position_jitterdodge(), alpha = 0.5, 
             aes(x = TempTreatment, color = PhTreatment)) +
  theme(legend.position = "right") +
  guides(color = guide_legend(title = "Temperature treatment")) + 
  labs(x = "pH treatment",
       y = "CR (L/hr)")
  theme_classic()

CRstd_box + theme(axis.title = element_text(size = 16),
                  axis.text = element_text(size = 14, color = "black"),
                  legend.title = element_text(size = 16),
                  legend.text = element_text(size = 14),
                  strip.text.x = element_text(size = 16))

dev.off()

CRstd_box

```

```{r, CR_twowayaov_boxplotV2_SimpleTemplate, error = F, message = F}

png("C:/Users/molly/Desktop/research/steeves + munroe - surfclam OA (rios 2023)/data + code/SurfclamsOAandTemp_Fall2023/CR_Std_Box2.png", width = 500, height = 350)

CRstd_box2 <- ggplot(surfclams, aes(y = CR_Std_Weight, 
                                    x=TempTreatment, 
                                    fill=PhTreatment, 
                                    order=PhTreatment))+
  geom_boxplot()+
  geom_point(aes(colour = PhTreatment), 
             position = position_jitterdodge(),
             alpha = 0.6)+
  scale_x_discrete(labels = c('Low', 'Medium', 'High'))+ ##check this
  theme(axis.ticks.length=unit(.5, "cm"))+
  scale_color_npg() +
  scale_fill_npg() +
  theme_classic2() +
  xlab("")+
  ylab("Clearance rate\n(L/hr)")+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2), legend.position= "none")+
  theme(text = element_text(size = 15))+
  labs(fill = "pH treatment")+
  labs(colour = "pH treatment")+
  geom_pwc(inherit.aes = TRUE,method = "t_test", 
           label = "p.adj.format",
           bracket.nudge.y = +0.1) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
  #stat_compare_means(label="p.format")
  #stat_compare_means(aes(group = Treatment), label = "p.format")

print(CRstd_box2)

dev.off()

CRstd_box2

```
